FROM node:22.13.0-bookworm-slim AS builder
WORKDIR /src
COPY web/package*.json ./
RUN npm ci
COPY web ./
RUN npm run build
FROM nginxinc/nginx-unprivileged:1.28.0-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /src/dist /usr/share/nginx/html
